POST http://localhost:8011/
Content-Type: application/json

{
   "name":"TRACE +mEVENT",
   "date":"21/12/2019",
   "phone_number":"+254700716563",
   "type":"event"}


####

GET http://localhost:8011/li

###

POST http://localhost:8011/whatsapp
Content-Type: application/json

{
   "name":"TRACE +mEVENT",
   "date":"21/12/2019",
   "phone_number":"+254700716563",
   "type":"event"
}

